# Generated by Django 3.1.7 on 2021-03-25 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('courier_type', models.CharField(max_length=5)),
                ('regions', models.CharField(max_length=200)),
                ('working_hours', models.CharField(max_length=200)),
                ('assign_time', models.DateTimeField(default=datetime.datetime(2021, 3, 25, 21, 18, 18, 204538))),
                ('last_time', models.DateTimeField(default=datetime.datetime(2021, 3, 25, 21, 18, 18, 204538))),
                ('orders', models.CharField(default='[]', max_length=200)),
                ('last_assign_courier_type', models.CharField(max_length=5)),
                ('earnings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('delivery_hours', models.CharField(max_length=200)),
                ('taken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Value_coruier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.IntegerField()),
                ('region', models.IntegerField()),
                ('sum_time', models.FloatField(default=0)),
                ('counts', models.IntegerField(default=0)),
            ],
        ),
    ]
