# Generated by Django 3.1.7 on 2021-03-27 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0010_auto_20210327_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='assign_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 13, 34, 24, 340619)),
        ),
        migrations.AlterField(
            model_name='courier',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 13, 34, 24, 340636)),
        ),
    ]
